### ISSUE TITLE
LateInitializationError: Field '_cameraController' has not been initialized.

### ISSUE THREAD

**Issue by jonasbeyer** [gabuldev/camera_camera#51]
The field `_cameraController` should be nullable to prevent that `dispose` is called before the controller has been initialized.

```
void startPreview(
  ResolutionPreset resolutionPreset,
) async {
    await _cameraController.dispose();
    ...

    _cameraController = CameraCameraController(
      ...
    );
```

**Comment by mattermoran** [comment]
Sent a PR https://github.com/gabuldev/camera_camera/pull/52

Before it gets merged and released can be installed from github directly:
```yaml
camera_camera:
    git:
      url: https://github.com/mattermoran/camera_camera.git
      ref: master
```
