### ISSUE TITLE
plugin is not compatible with latest sdk version of flutter

### ISSUE THREAD

**Issue by Rushi-tecocraft** [gabuldev/camera_camera#87]
![Screenshot 2022-04-01 at 6 19 57 PM](https://user-images.githubusercontent.com/100359719/161266919-1a52a4cf-f49c-4701-9548-d5b11cd29288.png)
![Screenshot 2022-04-01 at 6 20 25 PM](https://user-images.githubusercontent.com/100359719/161267002-fa954aca-6fdf-4fe0-94e1-6dca327a2a74.png)
![Screenshot 2022-04-01 at 6 20 56 PM](https://user-images.githubusercontent.com/100359719/161267066-c1ee7d36-f528-4db6-a4f0-2cd5f7ce9888.png)

Flutter sdk version : 2.10.3
In pubspec.yaml camera_camera: ^2.0.2 version is used.

**Comment by nietsmmar** [comment]
Same problem here :/

**Comment by EgonHoltz** [comment]
Same problem on sdk version 2.10.5... Anybody found out a workaround?

**Comment by RogerBrusamarello** [comment]
Any updates?

**Comment by kArtDevelopers** [comment]
Fixed this concern 

Write below written code in **pubspec.yaml** file 
```
camera_camera:
    git:
      url: https://github.com/kArtDevelopers/camera_camera.git
      ref: 661c52a747d114ef0f09d217319fdd261fddfba5    #branch name
```

and comment

> #camera_camera: ^2.0.2
